sonar.projectKey=SampleDotNetProject
sonar.working.directory=/workspace/.sonarqube/out/.sonar
sonar.projectBaseDir=/workspace
sonar.pullrequest.cache.basepath=/workspace

251844A8-455C-4A72-89D5-23196EC6EF35.sonar.projectKey=SampleDotNetProject:251844A8-455C-4A72-89D5-23196EC6EF35
251844A8-455C-4A72-89D5-23196EC6EF35.sonar.projectName=SampleDotNetProject
251844A8-455C-4A72-89D5-23196EC6EF35.sonar.projectBaseDir=/workspace
251844A8-455C-4A72-89D5-23196EC6EF35.sonar.sourceEncoding=utf-8
251844A8-455C-4A72-89D5-23196EC6EF35.sonar.tests=
251844A8-455C-4A72-89D5-23196EC6EF35.sonar.sources=\
"/workspace/Program.cs",\
"/workspace/obj/Release/netcoreapp3.1/.NETCoreApp,Version=v3.1.AssemblyAttributes.cs",\
"/workspace/obj/Release/netcoreapp3.1/SampleDotNetProject.AssemblyInfo.cs",\
"/workspace/PublishOutput/PublishOutput/web.config",\
"/workspace/PublishOutput/web.config",\
"/workspace/PublishOutput/PublishOutput/SampleDotNetProject.deps.json",\
"/workspace/PublishOutput/PublishOutput/SampleDotNetProject.runtimeconfig.json",\
"/workspace/PublishOutput/SampleDotNetProject.deps.json",\
"/workspace/PublishOutput/SampleDotNetProject.runtimeconfig.json",\
"/workspace/Dockerfile",\
"/workspace/PublishOutput/SampleDotNetProject",\
"/workspace/PublishOutput/SampleDotNetProject.pdb",\
"/workspace/README.md",\
"/workspace/run_test.sh",\
"/workspace/obj/project.assets.json",\
"/workspace/obj/SampleDotNetProject.csproj.nuget.dgspec.json",\
"/workspace/bin/Release/netcoreapp3.1/SampleDotNetProject.deps.json",\
"/workspace/bin/Release/netcoreapp3.1/SampleDotNetProject.runtimeconfig.dev.json",\
"/workspace/bin/Release/netcoreapp3.1/SampleDotNetProject.runtimeconfig.json",\
"/workspace/PublishOutput/PublishOutput/PublishOutput/SampleDotNetProject.deps.json",\
"/workspace/PublishOutput/PublishOutput/PublishOutput/SampleDotNetProject.runtimeconfig.json",\
"/workspace/PublishOutput/PublishOutput/PublishOutput/web.config",\
"/workspace/bin/Release/netcoreapp3.1/PublishOutput/SampleDotNetProject.deps.json",\
"/workspace/bin/Release/netcoreapp3.1/PublishOutput/SampleDotNetProject.runtimeconfig.json",\
"/workspace/bin/Release/netcoreapp3.1/PublishOutput/web.config",\
"/workspace/bin/Release/netcoreapp3.1/PublishOutput/PublishOutput/SampleDotNetProject.deps.json",\
"/workspace/bin/Release/netcoreapp3.1/PublishOutput/PublishOutput/SampleDotNetProject.runtimeconfig.json",\
"/workspace/bin/Release/netcoreapp3.1/PublishOutput/PublishOutput/web.config"

251844A8-455C-4A72-89D5-23196EC6EF35.sonar.cs.analyzer.projectOutPaths=\
"/workspace/.sonarqube/out/0"
251844A8-455C-4A72-89D5-23196EC6EF35.sonar.cs.roslyn.reportFilePaths=\
"/workspace/.sonarqube/out/0/Issues.json"
251844A8-455C-4A72-89D5-23196EC6EF35.sonar.cs.scanner.telemetry=\
"/workspace/.sonarqube/out/0/Telemetry.json"

251844A8-455C-4A72-89D5-23196EC6EF35.sonar.working.directory=/workspace/.sonarqube/out/.sonar/mod0
sonar.host.url=http://host.docker.internal:9000
sonar.visualstudio.enable=false

sonar.modules=251844A8-455C-4A72-89D5-23196EC6EF35

