FROM gitlab/gitlab-runner:ubuntu-v16.11.3

# 安裝 Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    usermod -aG docker gitlab-runner

# 🌟 核心修正：覆寫啟動指令，確保啟動時 Socket 權限正確
ENTRYPOINT ["/usr/bin/bash", "-c", "chmod 666 /var/run/docker.sock && /usr/bin/dumb-init /entrypoint main"]