stages:
  - build
  - docker_package

variables:
  GIT_REPO_NAME: "sample-node-web"

# 宣告全局 Cache，讓 npm 不用每次重新下載套件
cache:
  key: "npm-cache"
  paths:
    - .npm/

build_nuxt_app:
  stage: build
  image: god-ci-image:latest 
  script:
    - echo "開始設定 npm cache 路徑並打包..."
    - npm config set cache $(pwd)/.npm --global
    - bash run_test.sh
  artifacts:
    paths:
      - PublishOutput/

# 將打包好的產出物包進輕量級 Node.js Image
docker_package:
  stage: docker_package
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-node-app:latest .
  needs:
    - build_nuxt_app
